// Example of Root macro to copy a subset of a Tree to a new Tree 
// The input file has been generated by the program in $ROOTSYS/test/Event
// with Event 1000

void copytree()
{
    gSystem -> Load("$ROOTSYS/test/libEvent");

    //Get old file, old tree and set top branch address 
    TFile *oldfile = new TFile("$RootSYS/test/Event.root");//Declare a TFile class pointer and open the file  
    TTree *oldtree = (TTree*)oldfile -> Get ("T"); //Declare a TTree class pointer and Get the 
    Event *event = new Event(); // Declare a Event class pointer 
    oldtree -> SetBranchAddress("event",&event);
    oldtree -> SetBranchStatus("*",0);// Do NOT process all the Branches ; "*" means all , 0 means DO NOT PROCESS
    oldtree -> SetBranchStatus("event",1);// DO process the Branch event; "event" is the name of the branch "1" means DO PROCESS
    oldtree -> SetBranchStatus("fNtrack",1);
    oldtree -> SetBranchStatus("fNseg",1);
    oldtree -> SetBranchStatus("fH",1);

    //Create a new file + a clone of old tree in the new file 
    TFile *newfile = new TFile("small.root","recreate");//create a TFile class pointer , create a new root file and name it "small"
    TTree *newtree = oldtree -> CloneTree();//Create a clone of this tree and copy nentries.

    newtree -> Print();//Print a summary of the tree contents.
    newtree -> Write();//Write this object to the current directory.

    delete oldfile;// releasing the memory
    delete newfile;// releasing the memory
}
